export * from './user.model';
export * from './paciente.model';
export * from './medico.model';
export * from './especialidad.model';
export * from './turno.model';
export * from './ubicacion.model';
export * from './historia-clinica.model';
export * from './receta.model';
export * from './reporte.model';
